{{- if .Values.backend.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  labels:
    {{- include "fractal-flame.labels" . | nindent 4 }}
data:
  config.json: |
{{ .Files.Get "config/config.json" | indent 4 }}
{{- end }}
