apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    {{- include "fractal-flame.labels" . | nindent 4 }}
    {{- include "fractal-flame.backend.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "fractal-flame.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fractal-flame.labels" . | nindent 8 }}
        {{- include "fractal-flame.backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
              name: http
          env:
            - name: APP_PORT
              value: "{{ .Values.backend.port | toString }}"
            {{- if .Values.backend.config.enabled }}
            - name: CONFIG_PATH
              value: /app/config/config.json
            {{- end }}
          {{- if .Values.backend.config.enabled }}
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- if .Values.backend.config.enabled }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-backend-config
      {{- end }}
